name: Bearer CLI SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Bearer CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/install.sh | sh

    - name: Run Bearer scan
      run: |
        ./bin/bearer scan . --format sarif > results.sarif
