name: Bearer SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bearer-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bearer scan
        uses: bearer/bearer-action@v2
        with:
          path: .
          format: sarif
          output: bearer-output.sarif
        continue-on-error: true

      - name: Upload SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bearer-output.sarif
